### PR TITLE
SLING-8970 - adding test & fixing logic to consider inherited exports…

### PR DESCRIPTION
**Pull request by DominikSuess**
… in region checks

### CODE REVIEW

**Comment by bosschaert** [comment]
The tests have exposed some NPEs, @DominikSuess maybe look at those first and then update the PR?

**Comment by bosschaert** [comment]
@suess just wondering if you are planning to fix the test failures here?

**Comment by bosschaert** [comment]
@DominikSuess now there are merge conflicts...

**Comment by bosschaert** [comment]
@DominikSuess is this PR still active?

**Comment by cziegeler** [comment]
Closing as the related issue has been closed time ago

**Pull request closed without merging**
